# Site settings
title: SharpShooting
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about software development, mobile apps, cloud services and CRM.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sharpshooting.github.io" # the base hostname & protocol for your site
twitter_username: chemendonca
github_username:  sharpshooting

# Build settings
markdown: kramdown
#highlighter: rouge

gems:
- jekyll-sitemap